# Generated by Django 5.1 on 2026-06-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="visualizacoes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
