# Generated by Django 5.1 on 2026-06-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_video_visualizacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="visualizacoes",
            field=models.PositiveIntegerField(default=0, verbose_name="Visualizações"),
        ),
    ]
