# Generated by Django 5.1 on 2026-06-25 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_video_visualizacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="nota",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
